# SPDX-FileCopyrightText: 2026 AOT Technologies
#
# SPDX-License-Identifier: Apache-2.0

# REUSE-IgnoreStart
# String literals below emit SPDX headers into generated files; ignore them here.

"""Emit staged connector dual layout from DeriveResult."""

from __future__ import annotations

import json
import logging
import re
import textwrap
from pathlib import Path
from typing import Any

from nw_connector_builder.derive.operations import DeriveResult

logger = logging.getLogger(__name__)

# Every value interpolated into generated Python/TOML source must either be
# constrained to this safe character set or passed through repr()/an escaper
# first — never spliced raw into a string literal. connector_id also becomes
# a Python identifier fragment (class/module names), so this is required for
# correctness, not just safety.
_CONNECTOR_ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _validate_connector_id(connector_id: str) -> None:
    if not _CONNECTOR_ID_RE.fullmatch(connector_id):
        raise ValueError(
            f"invalid connector_id {connector_id!r}: must match {_CONNECTOR_ID_RE.pattern!r}"
        )


def _py_type(hint: str, required: bool, default: Any) -> str:
    if (
        hint in {"str", "int", "float", "bool"}
        or hint.startswith("list[")
        or hint.startswith("dict[")
    ):
        base = hint
    else:
        # Unresolved / unknown names → Any (never emit dangling class refs).
        base = "Any"
    if not required and default is None:
        return f"{base} | None"
    return base


def _field_extra(plan_param) -> str:  # noqa: ANN001
    style = repr(plan_param.style) if plan_param.style is not None else "None"
    explode = repr(plan_param.explode) if plan_param.explode is not None else "None"
    media = repr(plan_param.media_type) if plan_param.media_type is not None else "None"
    return (
        "{"
        f'"nw_in": {plan_param.location!r}, '
        f'"nw_wire_name": {plan_param.wire_name!r}, '
        f'"nw_style": {style}, '
        f'"nw_explode": {explode}, '
        f'"nw_media_type": {media}'
        "}"
    )


def _example_placeholder(param) -> Any:  # noqa: ANN001
    if param.default is not None:
        return param.default
    hint = param.python_type_hint
    if hint == "int":
        return 1
    if hint == "bool":
        return True
    if hint == "float":
        return 1.0
    if hint.startswith("list["):
        return []
    if hint.startswith("dict["):
        return {}
    return "example"


def generate_schema_module(connector_id: str, result: DeriveResult) -> str:
    """Hand-roll input envelopes; use Any/dict for complex body/output when needed."""
    _validate_connector_id(connector_id)
    lines: list[str] = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "from typing import Any, Literal",
        "",
        "from pydantic import BaseModel, ConfigDict, Field",
        "",
        "from node_wire_runtime import RestResponseOutput",
        "",
        "",
    ]

    # Shared body/output placeholders as dict wrappers when schemas exist
    for action in result.actions:
        in_name = _pascal(action.name) + "Input"
        out_name = _pascal(action.name) + "Output"
        lines.append(f"class {in_name}(BaseModel):")
        lines.append('    model_config = ConfigDict(populate_by_name=True, extra="forbid")')
        lines.append(f"    action: Literal[{action.name!r}] = {action.name!r}")
        for p in action.params:
            typ = _py_type(p.python_type_hint, p.required, p.default)
            alias = ""
            if p.field_name != p.wire_name:
                alias = f", alias={p.wire_name!r}"
            default = "..."
            if not p.required:
                default = repr(p.default) if p.default is not None else "None"
            lines.append(
                f"    {p.field_name}: {typ} = Field("
                f"{default}{alias}, json_schema_extra={_field_extra(p)})"
            )
        if action.body_schema is not None:
            # dict[str, Any] (not bare Any) so MCP inputSchema is a valid object
            # schema — Pydantic emits anyOf[{}, null] for Any, which clients reject.
            body_extra = {
                "nw_in": "body",
                "nw_wire_name": "body",
                "nw_style": None,
                "nw_explode": None,
                "nw_media_type": action.body_media_type or "application/json",
            }
            lines.append(
                f"    body: dict[str, Any] | None = Field(None, json_schema_extra={body_extra!r})"
            )
        if len(action.params) == 0 and action.body_schema is None:
            lines.append("    pass")
        lines.append("")
        lines.append("")

        if action.use_rest_response_output:
            lines.append(f"{out_name} = RestResponseOutput")
        else:
            # Object-shaped success schema only (see _success_response_schema).
            lines.append(f"class {out_name}(BaseModel):")
            lines.append('    model_config = ConfigDict(extra="allow")')
            lines.append("    # OpenAPI object success schema — permissive allow for nested props")
            lines.append("    pass")
        lines.append("")
        lines.append("")

    return "\n".join(lines)


def _pascal(snake: str) -> str:
    return "".join(p.capitalize() for p in snake.split("_") if p)


def generate_logic_module(connector_id: str, result: DeriveResult) -> str:
    _validate_connector_id(connector_id)
    class_name = _pascal(connector_id) + "Connector"
    imports_in = []
    imports_out = []
    for a in result.actions:
        imports_in.append(_pascal(a.name) + "Input")
        imports_out.append(_pascal(a.name) + "Output")

    lines = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "from typing import ClassVar, Dict, Tuple, Type",
        "",
        "import httpx",
        "from pydantic import BaseModel",
        "",
        "from node_wire_runtime import RestConnector, RestResponseOutput, nw_action",
        "from node_wire_runtime.models import ErrorCategory",
        "",
        "from .schema import (",
    ]
    for name in sorted(set(imports_in + imports_out)):
        lines.append(f"    {name},")
    lines += [
        ")",
        "",
        "",
        f"class {class_name}(RestConnector):",
        f'    """Generated OpenAPI connector ``{connector_id}``."""',
        "",
        f"    connector_id = {connector_id!r}",
        f"    default_base_url = {result.default_base_url!r}",
        "    output_model: ClassVar[Type[BaseModel]] = RestResponseOutput",
        "    _nw_abstract_base = False",
        "",
        "    # RestConnector.execute_rest raises these; without a mapping every one",
        "    # of them would default to FATAL and never retry (see execute_rest in",
        "    # node_wire_runtime/rest.py). SsrfBlockedError is intentionally left",
        "    # unmapped for now.",
        "    error_map: ClassVar[Dict[Type[BaseException], Tuple[ErrorCategory, str]]] = {",
        '        httpx.TimeoutException: (ErrorCategory.RETRYABLE, "HTTP_TIMEOUT"),',
        '        httpx.ConnectError: (ErrorCategory.RETRYABLE, "HTTP_CONNECT_ERROR"),',
        '        httpx.ReadTimeout: (ErrorCategory.RETRYABLE, "HTTP_READ_TIMEOUT"),',
        '        httpx.RequestError: (ErrorCategory.FATAL, "HTTP_REQUEST_ERROR"),',
        '        httpx.HTTPStatusError: (ErrorCategory.BUSINESS, "HTTP_STATUS_ERROR"),',
        "    }",
        "",
    ]

    for a in result.actions:
        in_name = _pascal(a.name) + "Input"
        out_name = _pascal(a.name) + "Output"
        auth_kw = "" if a.auth else ", auth=False"
        decorator_kw = "" if a.auth else ", requires_auth=False"
        # auth_scheme_name is an OpenAPI securitySchemes key — always emit via !r.
        scheme_kw = f", auth_scheme={a.auth_scheme_name!r}" if a.auth_scheme_name else ""
        lines += [
            f'    @nw_action("{a.name}"{decorator_kw})',
            f"    async def {a.name}(self, params: {in_name}, *, trace_id: str) -> {out_name}:",
            "        return await self.execute_rest(",
            f'            method="{a.method}",',
            f"            path_template={a.path!r},",
            "            params=params,",
            f"            output_model={out_name},",
            f"            trace_id=trace_id{auth_kw}{scheme_kw},",
            "        )",
            "",
        ]
    return "\n".join(lines)


def generate_init_module(connector_id: str) -> str:
    _validate_connector_id(connector_id)
    return textwrap.dedent(
        f'''\
        # Generated by nw-connector-builder — do not hand-edit.
        # SPDX-FileCopyrightText: 2026 AOT Technologies
        # SPDX-License-Identifier: Apache-2.0
        """node_wire_{connector_id} connector package."""
        '''
    )


def generate_package_pyproject(connector_id: str) -> str:
    _validate_connector_id(connector_id)
    dist = connector_id.replace("_", "-")
    return textwrap.dedent(
        f"""\
        # Generated by nw-connector-builder — do not hand-edit.
        # SPDX-FileCopyrightText: 2026 AOT Technologies
        # SPDX-License-Identifier: Apache-2.0

        [project]
        name = "node-wire-{dist}"
        version = "1.0.0"
        description = "Node Wire connector — {connector_id} (OpenAPI-generated)"
        requires-python = ">=3.11"
        license = "Apache-2.0"
        authors = [{{ name = "AOT Technologies", email = "opensource@aot-technologies.com" }}]

        dependencies = [
            "node-wire-runtime>=1.0.0",
            "httpx[http2]>=0.27.0,<0.28.0",
        ]

        [project.optional-dependencies]
        test = [
            "pytest>=8.0.0",
            "polyfactory>=2.16.0",
        ]

        [project.entry-points."node_wire.connectors"]
        {connector_id} = "node_wire_{connector_id}.logic"

        [build-system]
        requires = ["setuptools>=69.0.0", "cython>=3.0", "wheel"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools.packages.find]
        where = ["../../../src"]
        include = ["node_wire_{connector_id}*"]

        [tool.pytest.ini_options]
        testpaths = ["tests"]
        """
    )


def generate_model_tests(connector_id: str, result: DeriveResult) -> str:
    _validate_connector_id(connector_id)
    lines = [
        "# Generated by nw-connector-builder — do not hand-edit.",
        "# SPDX-FileCopyrightText: 2026 AOT Technologies",
        "# SPDX-License-Identifier: Apache-2.0",
        "from __future__ import annotations",
        "",
        "import json",
        "",
        "from polyfactory.factories.pydantic_factory import ModelFactory",
        "",
        f"from node_wire_{connector_id} import schema as sch",
        "",
    ]
    for a in result.actions:
        in_name = _pascal(a.name) + "Input"
        lines += [
            f"def test_{a.name}_input_roundtrip() -> None:",
            "    class _F(ModelFactory):",
            f"        __model__ = sch.{in_name}",
            "    inst = _F.build()",
            "    data = inst.model_dump(by_alias=True)",
            f"    again = sch.{in_name}.model_validate(data)",
            f"    assert again.action == {a.name!r}",
            "",
        ]
        if a.examples.get("request") is not None and a.body_schema is not None:
            # Build a payload that satisfies required path/query/header fields so
            # the example→model gate does not abort on otherwise-valid specs.
            payload_bits = [f"'action': {a.name!r}", "'body': example"]
            for p in a.params:
                if not p.required:
                    continue
                payload_bits.append(f"{p.field_name!r}: {json.dumps(_example_placeholder(p))}")
            payload_expr = "{" + ", ".join(payload_bits) + "}"
            lines += [
                f"def test_{a.name}_example_parses() -> None:",
                f"    example = {json.dumps(a.examples['request'])}",
                f"    payload = {payload_expr}",
                f"    sch.{in_name}.model_validate(payload)",
                "",
            ]
    return "\n".join(lines)


def write_staging(
    staging: Path,
    connector_id: str,
    result: DeriveResult,
    report: dict[str, Any],
) -> None:
    _validate_connector_id(connector_id)
    src_pkg = staging / "src" / f"node_wire_{connector_id}"
    pkg = staging / "packages" / "connectors" / connector_id
    tests = pkg / "tests"
    fixtures = tests / "fixtures"
    src_pkg.mkdir(parents=True, exist_ok=True)
    tests.mkdir(parents=True, exist_ok=True)
    fixtures.mkdir(parents=True, exist_ok=True)

    (src_pkg / "__init__.py").write_text(generate_init_module(connector_id), encoding="utf-8")
    (src_pkg / "schema.py").write_text(
        generate_schema_module(connector_id, result), encoding="utf-8"
    )
    (src_pkg / "logic.py").write_text(generate_logic_module(connector_id, result), encoding="utf-8")
    (pkg / "pyproject.toml").write_text(generate_package_pyproject(connector_id), encoding="utf-8")
    (tests / f"test_{connector_id}_models.py").write_text(
        generate_model_tests(connector_id, result), encoding="utf-8"
    )
    (tests / "__init__.py").write_text("", encoding="utf-8")
    (pkg / "report.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    logger.info("Wrote staging tree under %s", staging)


# REUSE-IgnoreEnd
